services:
  kaia-agent-analytics:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    # NOTE: Uncomment to show logs to files (only if it is enabled in logger.ts)
    # volumes:
      # Logs volume not needed as file logging has been disabled
      # - ./logs:/app/logs