services:
  kaia-agent-analytics:
    image: ghcr.io/kaiachain/kaia-agent-analytics:latest
    restart: always
    env_file:
      - .env.prod
    volumes:
      - ./logs:/app/logs
    environment:
      - TZ=${TZ:-Asia/Singapore}
      - NODE_ENV=production 